services:
  grafana:
    image: grafana/grafana
    container_name: grafana_bench
    networks:
      - net
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - net
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus_data:/prometheus
    depends_on:
      - cadvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    networks:
      - net
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
  myrocks:
    image: percona/percona-server:5.7
    container_name: myrocks_btree_and_lsmtree
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: --plugin-load-add=ha_rocksdb.so
    volumes:
      - ./rocksdb_data:/var/lib/mysql
    cpus: 1
    mem_limit: 1G
    shm_size: 1G
    networks:
      - net
    restart: always
  postgres:
    image: postgres:bullseye
    container_name: postgres_btree
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    cpus: 1
    mem_limit: 1G
    shm_size: 1G
    restart: always
    networks:
      - net
  cockroachdb:
    image: cockroachdb/cockroach:v25.2.2
    container_name: cockroachdb
    ports:
      - 26257:26257
    command: start-single-node --insecure
    volumes:
      - ./cockroachdb_data:/cockroach/cockroach-data
    cpus: 1
    mem_limit: 1G
    shm_size: 1G
    restart: always
    networks:
      - net

networks:
  net:
    driver: bridge
